### ISSUE TITLE
[BUG] Unconfirmed problem running `npm run dev` on arm64

### ISSUE THREAD

**Issue by mabolek** [t3kit/t3kit-starter#59]
**Describe the bug**

This bug is not fully confirmed yet. I'm posting it here to make sure others can find it, in which case the issue will be confirmed.

I got this error when trying to run `npm run dev` on arm64 (Macbook Pro M1) in a DDEV container (which might also be a reason for the error). Removing the default subtheme "fixed" the issue. As I'm not using the subtheme, removing it was fine and I haven't made any further checks.

Running `npm run dev`:

```
## There is an issue with `node-fibers` ##
`/var/www/html/node_modules/fibers/bin/linux-arm64-83-glibc/fibers.node` is missing.

Try running this to fix the issue: /usr/bin/node /var/www/html/node_modules/fibers/build
Error: Cannot find module '/var/www/html/node_modules/fibers/bin/linux-arm64-83-glibc/fibers'
Require stack:
- /var/www/html/node_modules/fibers/fibers.js
- /var/www/html/public/typo3conf/ext/t3kit/theme/config/sass/index.js
- /var/www/html/public/typo3conf/ext/theme_newcustomproject/theme/config/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/var/www/html/node_modules/fibers/fibers.js:14:39)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
/var/www/html/node_modules/fibers/fibers.js:23
		throw new Error('Missing binary. See message above.');
		^

Error: Missing binary. See message above.
    at Object.<anonymous> (/var/www/html/node_modules/fibers/fibers.js:23:9)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/var/www/html/public/typo3conf/ext/t3kit/theme/config/sass/index.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
npm ERR! Lifecycle script `build-dev` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: theme_newcustomproject@10.0.0 
npm ERR!   at location: /var/www/html/public/typo3conf/ext/theme_newcustomproject 
Failed to execute command npm run dev: exit status 1
```

Running `/usr/bin/node /var/www/html/node_modules/fibers/bu
ild`:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@8.1.0
gyp info using node@14.17.0 | linux | arm64
gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v14.17.0/node-v14.17.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v14.17.0/node-v14.17.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v14.17.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v14.17.0/SHASUMS256.txt
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/var/www/html/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/mathias/.cache/node-gyp/14.17.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/mathias/.cache/node-gyp/14.17.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/mathias/.cache/node-gyp/14.17.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/var/www/html',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: /var/www/html) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:353:16)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.10.25-linuxkit
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild" "--release"
gyp ERR! cwd /var/www/html
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v8.1.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
Failed to execute command /usr/bin/node /var/www/html/node_modules/fibers/build: exit status 1
```

**To Reproduce**

See above description and commands.

**Expected behavior**

Output from `npm run dev` should be:

```
> dev
> npm run build-dev -ws
```

**Screenshots**
n/a

**Desktop (please complete the following information):**

- OS: Mac OS 11.4 (20F71)
- Architecture: arm64
- DDEV: v1.17.5

**Comment by Shalashtein** [comment]
Getting the same exact error with a nuxt project, running `npm run dev` launches the project normally, however when I launch it through docker I get 

```
ERROR  Error: Cannot find module '/app/node_modules/fibers/bin/linux-arm64-83-glibc/fibers'
adminapp     | Require stack:
adminapp     | - /app/node_modules/fibers/fibers.js
adminapp     | - /app/node_modules/sass-loader/dist/utils.js
adminapp     | - /app/node_modules/sass-loader/dist/index.js
adminapp     | - /app/node_modules/sass-loader/dist/cjs.js
adminapp     | - /app/node_modules/webpack/node_modules/loader-runner/lib/loadLoader.js
adminapp     | - /app/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js
adminapp     | - /app/node_modules/webpack/lib/NormalModule.js
adminapp     | - /app/node_modules/webpack/lib/NormalModuleFactory.js
adminapp     | - /app/node_modules/webpack/lib/Compiler.js
adminapp     | - /app/node_modules/webpack/lib/webpack.js
adminapp     | - /app/node_modules/@nuxt/webpack/dist/webpack.js
adminapp     | - /app/node_modules/@nuxt/builder/dist/builder.js
adminapp     | - /app/index.js
adminapp     |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
adminapp     |     at Function.Module._load (internal/modules/cjs/loader.js:745:27)
adminapp     |     at Module.require (internal/modules/cjs/loader.js:961:19)
adminapp     |     at require (internal/modules/cjs/helpers.js:92:18)
adminapp     |     at Object.<anonymous> (/app/node_modules/fibers/fibers.js:14:39)
adminapp     |     at Module._compile (internal/modules/cjs/loader.js:1072:14)
adminapp     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
adminapp     |     at Module.load (internal/modules/cjs/loader.js:937:32)
adminapp     |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
adminapp     |     at Module.require (internal/modules/cjs/loader.js:961:19)
adminapp     |     at require (internal/modules/cjs/helpers.js:92:18)
adminapp     |     at getSassOptions (/app/node_modules/sass-loader/dist/utils.js:140:25)
adminapp     |     at Object.loader (/app/node_modules/sass-loader/dist/index.js:43:55)
adminapp     |     at LOADER_EXECUTION (/app/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
adminapp     |     at runSyncOrAsync (/app/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
adminapp     |     at iterateNormalLoaders (/app/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
adminapp     |
adminapp     |
adminapp     |  ERROR  Missing binary. See message above.
adminapp     |
adminapp     |   at Object.<anonymous> (node_modules/fibers/fibers.js:23:9)
adminapp     |   at Module._compile (internal/modules/cjs/loader.js:1072:14)
adminapp     |   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
adminapp     |   at Module.load (internal/modules/cjs/loader.js:937:32)
adminapp     |   at Function.Module._load (internal/modules/cjs/loader.js:778:12)
adminapp     |   at Module.require (internal/modules/cjs/loader.js:961:19)
adminapp     |   at require (internal/modules/cjs/helpers.js:92:18)
adminapp     |   at getSassOptions (node_modules/sass-loader/dist/utils.js:140:25)
adminapp     |   at Object.loader (node_modules/sass-loader/dist/index.js:43:55)
adminapp     |   at LOADER_EXECUTION (node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
adminapp     |   at runSyncOrAsync (node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
adminapp     |   at iterateNormalLoaders (node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
adminapp     |   at Array.<anonymous> (node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
adminapp     |   at Storage.finished (node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
adminapp     |   at node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
adminapp     |   at node_modules/graceful-fs/graceful-fs.js:123:16
```

**Comment by MattiasNilsson** [comment]
I have just installed DDEV on a new arm64 (Macbook Pro M1). Then next step was to run `npm run` inside the DDEV container. I can confirm that this is not an issue!
